package humana.websecurity.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-07-29T16:59:43.880-07:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "urn:Humana:WebSecurity:WebServices", name = "AccessControlDriverWebServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class, humana.websecurity.sl.webservice.messagetypes.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccessControlDriverWebServiceHttpGet {

    /**
     * Retrieves Entities for the Specified User
     */
    @WebMethod(operationName = "GetUserEntityList")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserEntityList(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "businessFunctionGenKey", name = "businessFunctionGenKey", targetNamespace = "")
        java.lang.String businessFunctionGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * This method obtains the demographic data for organization
     */
    @WebMethod(operationName = "GetDemographicsForEntityEx")
    @WebResult(name = "ResponseGetDemographicsForEntity", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetDemographicsForEntity getDemographicsForEntityEx(
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey
    );

    /**
     * Retrieves PortOfOrigin for the given originGenKey
     */
    @WebMethod(operationName = "GetPortOfOrigin")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getPortOfOrigin(
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey
    );

    /**
     * Provides the same data as 'GetACLAccessIdsQualifiedForUser', but only allows limitation of response data based on function or menu template. Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOrigin
     */
    @WebMethod(operationName = "GetACLAccessIdsByKeyTypeForUserEx")
    @WebResult(name = "ResponseBFForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBFForUser getACLAccessIdsByKeyTypeForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * List Menu Templates for MenuGenKey and BusinessFunctionGenKey
     */
    @WebMethod(operationName = "GetMenuItemDetails")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getMenuItemDetails(
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "businessFunctionGenKey", name = "businessFunctionGenKey", targetNamespace = "")
        java.lang.String businessFunctionGenKey
    );

    /**
     * Retrieves GetAccessIdentEntityAssoc for given AccessID
     */
    @WebMethod(operationName = "GetAccessIdentEntityAssoc")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getAccessIdentEntityAssoc(
        @WebParam(partName = "accessId", name = "accessId", targetNamespace = "")
        java.lang.String accessId,
        @WebParam(partName = "accessIdTypeCd", name = "accessIdTypeCd", targetNamespace = "")
        java.lang.String accessIdTypeCd
    );

    /**
     * Provides Aka Name for a specific sessionID.
     */
    @WebMethod(operationName = "GetAKANameBySessionID")
    @WebResult(name = "Session", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public Session getAKANameBySessionID(
        @WebParam(partName = "sessionID", name = "sessionID", targetNamespace = "")
        java.lang.String sessionID
    );

    /**
     * Retrieves Entity Addresses for the given entityGenKey and originGenKey
     */
    @WebMethod(operationName = "GetEntityAddresses")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getEntityAddresses(
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey
    );

    /**
     * This web method is simular to the method 'GetACLFunctionsForUser' in that it supplies the same level 1, level 2 and level 3 information. However, it expands the reply to include level 4 information which represents data (Access Identifiers) for each function. In addition to being able to limit the reply data by Entity, Portal, or System Application, you can futher limit the reply to data about just one function.
     */
    @WebMethod(operationName = "GetACLFunctionWithAccessIdsForUserEx")
    @WebResult(name = "ResponseBFForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBFForUser getACLFunctionWithAccessIdsForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "function", name = "function", targetNamespace = "")
        java.lang.String function,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * Provides level 4 ACL information for a specific user. The method supports limiting the response set based on Organization or function.
     */
    @WebMethod(operationName = "GetACLAccessIdsQualifiedForUserEx")
    @WebResult(name = "ResponseBFForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBFForUser getACLAccessIdsQualifiedForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "function", name = "function", targetNamespace = "")
        java.lang.String function,
        @WebParam(partName = "menuTemplate", name = "menuTemplate", targetNamespace = "")
        java.lang.String menuTemplate,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Retrieves User Attributes for the given akaName and attrIdentifier
     */
    @WebMethod(operationName = "GetUserAttributes")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserAttributes(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "attrIdentifier", name = "attrIdentifier", targetNamespace = "")
        java.lang.String attrIdentifier
    );

    /**
     * Retrieves User ID for the given akaName
     */
    @WebMethod(operationName = "GetUserFromAkaName")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserFromAkaName(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName
    );

    /**
     * Returns a Boolean flag indicating if the User is Authorized for a certain Menu Template or Business Function.Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOriginApplicationNameEAPM ID
     */
    @WebMethod(operationName = "IsUserAuthorizedWithLoggingEx")
    @WebResult(name = "ResponseBoolRoot", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBool isUserAuthorizedWithLoggingEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "applicationName", name = "applicationName", targetNamespace = "")
        java.lang.String applicationName,
        @WebParam(partName = "eampId", name = "eampId", targetNamespace = "")
        java.lang.String eampId
    );

    /**
     * This method provides a level 1 ACL. Level 1 contains the user's demographic information. This method provides that information using the AKA Name as input. If all you know about this user is their User ID, see 'GetUserDemographicsByUserId' to obtain this same information.
     */
    @WebMethod(operationName = "GetUserDemographicsByAkaNameEx")
    @WebResult(name = "ResponseGetUserDemographics", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetUserDemographics getUserDemographicsByAkaNameEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName
    );

    /**
     * List AccessIdentifier, AccessIdentifierType, OragnizationName for AccessID, UserName, EntityName
     */
    @WebMethod(operationName = "GetAccessIDsForCCRs")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getAccessIDsForCCRs(
        @WebParam(partName = "accessID", name = "accessID", targetNamespace = "")
        java.lang.String accessID,
        @WebParam(partName = "userLastName", name = "userLastName", targetNamespace = "")
        java.lang.String userLastName,
        @WebParam(partName = "userFirstName", name = "userFirstName", targetNamespace = "")
        java.lang.String userFirstName,
        @WebParam(partName = "entityName", name = "entityName", targetNamespace = "")
        java.lang.String entityName,
        @WebParam(partName = "caLastName", name = "caLastName", targetNamespace = "")
        java.lang.String caLastName
    );

    /**
     * Retrieves Controlling Authorities for the given entityGenKey
     */
    @WebMethod(operationName = "GetEntityControllingAuthorities")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getEntityControllingAuthorities(
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey
    );

    /**
     * List Menu Templates for OriginGenKey and AkaName in XML format
     */
    @WebMethod(operationName = "GetUserMenusXML")
    @WebResult(name = "string", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public java.lang.String getUserMenusXML(
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "menuLevel", name = "menuLevel", targetNamespace = "")
        java.lang.String menuLevel,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * This method will provide a list of users that have a current association with an organization. Please NOTE: It does not return a user whose access has been revoked. Possible options for entityUserTypeCode are : All,PAA,AA, OA,
     */
    @WebMethod(operationName = "GetActiveUsersForEntityEx")
    @WebResult(name = "ResponseGetActiveUsersForEntity", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetActiveUsersForEntity getActiveUsersForEntityEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "entityUserTypeCode", name = "entityUserTypeCode", targetNamespace = "")
        java.lang.String entityUserTypeCode
    );

    /**
     * This method will return all attributes that have been assigned to an entity user. An entity user represents a relationship between a user and an organization. At the current time some of the Secured Logons installations have implemented entity user attributes, and others have not. An example of an entity user attribute would be TSO_ID.
     */
    @WebMethod(operationName = "GetAttributesForEntityUserEx")
    @WebResult(name = "ResponseGetAttributesForEntityUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetAttributesForEntityUser getAttributesForEntityUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "attributeName", name = "attributeName", targetNamespace = "")
        java.lang.String attributeName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "entityUserGenKey", name = "entityUserGenKey", targetNamespace = "")
        java.lang.String entityUserGenKey
    );

    /**
     * List SystemApplication for the SystemApplicationID
     */
    @WebMethod(operationName = "GetSystemApplicationRow")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getSystemApplicationRow(
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * Returns a Boolean flag indicating if the User is Authorized for a certain Menu Template or Business Function.Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOriginApplicationNameEAPM ID
     */
    @WebMethod(operationName = "IsUserAuthorizedBoolWithLoggingEx")
    @WebResult(name = "boolean", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public boolean isUserAuthorizedBoolWithLoggingEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "applicationName", name = "applicationName", targetNamespace = "")
        java.lang.String applicationName,
        @WebParam(partName = "eampId", name = "eampId", targetNamespace = "")
        java.lang.String eampId
    );

    /**
     * This method returns menu template information for a given user. The reply information can be limited by Orginization, Portal, System Application or Menu Template.
     */
    @WebMethod(operationName = "GetACLMenusForUserEx")
    @WebResult(name = "ResponseMenusForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseMenusForUser getACLMenusForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * This method is simular to 'GetOrganizationListForUser'. The difference is that with this method you can limit the organizations lists by including a menu template or business function in your request. When that is done, the reply set will only include organizations that have given this user permission to perform that business function or menu template.Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOrigin
     */
    @WebMethod(operationName = "GetOrgListQualifiedForUserEx")
    @WebResult(name = "ResponseOrganizationList", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseOrganizationList getOrgListQualifiedForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * This method will provide a list of organizations that have a an association with this user. Please NOTE: It does not return an organization if they have revoked this user's access.
     */
    @WebMethod(operationName = "GetOrganizationListForUserEx")
    @WebResult(name = "ResponseOrganizationList", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseOrganizationList getOrganizationListForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Retrieves Access Identifiers
     */
    @WebMethod(operationName = "GetAccessIdentifiers")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getAccessIdentifiers(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "idType", name = "idType", targetNamespace = "")
        java.lang.String idType,
        @WebParam(partName = "businessFunctionGenKey", name = "businessFunctionGenKey", targetNamespace = "")
        java.lang.String businessFunctionGenKey,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * This method provides a list of functions that belong to a single System Application.
     */
    @WebMethod(operationName = "GetFunctionListForSystemApplicationEx")
    @WebResult(name = "ResponseGetBFListForSystemApplication", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetBFListForSystemApplication getFunctionListForSystemApplicationEx(
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * Retrieves Entity Type for the given entityGenKey and originGenKey
     */
    @WebMethod(operationName = "GetEntityType")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getEntityType(
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey
    );

    /**
     * This method is used to obtain a list of user attributes. Within our current implementation, there are no user attributes currently being stored in the Secured Logons database. As a result, this method will always return zero attributes. If any attributes are ever added to the Secured Logons database, this method would return them.
     */
    @WebMethod(operationName = "GetAttributesForUserEx")
    @WebResult(name = "ResponseGetAttributesForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetAttributesForUser getAttributesForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "attributeName", name = "attributeName", targetNamespace = "")
        java.lang.String attributeName,
        @WebParam(partName = "userGenKey", name = "userGenKey", targetNamespace = "")
        java.lang.String userGenKey,
        @WebParam(partName = "userId", name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    /**
     * This method provides a User ACL at level 3. Level 3 provides ACL information about the user, the organizations the user is assocaited with, and it includes the functions the user has access to through those organizations. It does not supply inforamtion about the data (Access Identifiers) associated with each funtion. See the method 'GetACLFunctionWithAccessIdsForUser' to include the data. A complete or partial list of functions can be requested. It is best to request only the portion of the ACL you actually need. To limit the ACL's content you can provide an Entity Gen Key, an Origin Gen Key, and/or a System Application ID. When not limiting the ACL by any or all of these values supply a zero for the value. The zero will indicate that you do not want to limit by that value.
     */
    @WebMethod(operationName = "GetACLFunctionsForUserEx")
    @WebResult(name = "ResponseBFForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBFForUser getACLFunctionsForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * List Menu Templates for OriginGenKey and AkaName
     */
    @WebMethod(operationName = "GetUserMenus")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserMenus(
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "menuLevel", name = "menuLevel", targetNamespace = "")
        java.lang.String menuLevel,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Retrieves User EntitySegment list for the given akaName, businessFunctionGenKey and menuGenKey
     */
    @WebMethod(operationName = "GetUserEntitySegmentList")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserEntitySegmentList(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "businessFunctionGenKey", name = "businessFunctionGenKey", targetNamespace = "")
        java.lang.String businessFunctionGenKey,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey
    );

    /**
     * Retrieves the Segmented Access Identifiers for the given UserID and AccessIDTypeCode
     */
    @WebMethod(operationName = "GetSegmentedAccessIdentifiersForUser")
    @WebResult(name = "string", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public java.lang.String getSegmentedAccessIdentifiersForUser(
        @WebParam(partName = "userID", name = "userID", targetNamespace = "")
        java.lang.String userID,
        @WebParam(partName = "accessIDType", name = "accessIDType", targetNamespace = "")
        java.lang.String accessIDType
    );

    /**
     * Retrieves Function Access for the given AkaName, ApplicationID and SessionID
     */
    @WebMethod(operationName = "GetUserFunctionAccess")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getUserFunctionAccess(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "applicationID", name = "applicationID", targetNamespace = "")
        java.lang.String applicationID,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Get User Agreements from AkaName
     */
    @WebMethod(operationName = "GetUserAgreements")
    @WebResult(name = "ResponseGetUserAgreements", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetUserAgreements getUserAgreements(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName
    );

    /**
     * Provides complete level 4 ACL information for a specific User.
     */
    @WebMethod(operationName = "GetACLAccessIdsForUserEx")
    @WebResult(name = "ResponseBFForUser", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBFForUser getACLAccessIdsForUserEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Returns a Boolean flag indicating if the User is Authorized for a certain Menu Template or Business Function.Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOrigin
     */
    @WebMethod(operationName = "IsUserAuthorizedExBool")
    @WebResult(name = "boolean", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public boolean isUserAuthorizedExBool(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Get User DTO
     */
    @WebMethod(operationName = "GetUserDTOEx")
    @WebResult(name = "ResponseUserDTO", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseUserDTO getUserDTOEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "function", name = "function", targetNamespace = "")
        java.lang.String function,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * This method is simular to 'GetACLMenusForUser'. The difference is in the output format. This method returns menus in XML format.
     */
    @WebMethod(operationName = "GetACLMenusForUserAsXMLEx")
    @WebResult(name = "ResponseMenuXML", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseMenuXML getACLMenusForUserAsXMLEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId,
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId
    );

    /**
     * List Menu Templates for Port Of Origin
     */
    @WebMethod(operationName = "GetPortOfOriginMenus")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getPortOfOriginMenus(
        @WebParam(partName = "portOfOrigin", name = "portOfOrigin", targetNamespace = "")
        java.lang.String portOfOrigin,
        @WebParam(partName = "menuLevel", name = "menuLevel", targetNamespace = "")
        java.lang.String menuLevel,
        @WebParam(partName = "menuGenKey", name = "menuGenKey", targetNamespace = "")
        java.lang.String menuGenKey
    );

    /**
     * List SystemApplicationAtrribute for the SystemApplicationID
     */
    @WebMethod(operationName = "GetSystemApplicationAttributeRow")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getSystemApplicationAttributeRow(
        @WebParam(partName = "systemApplicationId", name = "systemApplicationId", targetNamespace = "")
        java.lang.String systemApplicationId,
        @WebParam(partName = "attributeNbr", name = "attributeNbr", targetNamespace = "")
        java.lang.String attributeNbr
    );

    /**
     * This method provides a level 1 ACL. Level 1 contains the user's demographic information. This method provides that information using the User Id as input. If all you know about this user is their AKA Name, see 'GetUserDemographicsByAkaName' to obtain this same information.
     */
    @WebMethod(operationName = "GetUserDemographicsByUserIdEx")
    @WebResult(name = "ResponseGetUserDemographics", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseGetUserDemographics getUserDemographicsByUserIdEx(
        @WebParam(partName = "userId", name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    /**
     * This method will provide a list of Access Identifiers assigned to an organization. It allows you to limit the reply set based on Access ID type. NOTE: The method is not within the context of a specific user. Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOrigin
     */
    @WebMethod(operationName = "GetACLAccessIdsForEntityEx")
    @WebResult(name = "ResponseEntityAID", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseEntityAID getACLAccessIdsForEntityEx(
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType
    );

    /**
     * Retrieves SystemNotifications
     */
    @WebMethod(operationName = "GetSystemNotifications")
    @WebResult(name = "DataSet", targetNamespace = "urn:Humana:WebSecurity:WebServices", partName = "Body")
    public DataSet getSystemNotifications(
        @WebParam(partName = "userTypeCd", name = "userTypeCd", targetNamespace = "")
        java.lang.String userTypeCd,
        @WebParam(partName = "originGenKey", name = "originGenKey", targetNamespace = "")
        java.lang.String originGenKey,
        @WebParam(partName = "entityTypeCd", name = "entityTypeCd", targetNamespace = "")
        java.lang.String entityTypeCd,
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName
    );

    /**
     * This method provides a way to locate what organizations are assocaited with a given Access Identifier. When using this method, be prepared to handle a list of organizations. Do not assume you will only get one.
     */
    @WebMethod(operationName = "GetEntityFromAssignedAccessIdEx")
    @WebResult(name = "ResponseOrganizationList", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseOrganizationList getEntityFromAssignedAccessIdEx(
        @WebParam(partName = "accessId", name = "accessId", targetNamespace = "")
        java.lang.String accessId,
        @WebParam(partName = "accessIdType", name = "accessIdType", targetNamespace = "")
        java.lang.String accessIdType,
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "entityGenKey", name = "entityGenKey", targetNamespace = "")
        java.lang.String entityGenKey,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    /**
     * Returns a Boolean flag indicating if the User is Authorized for a certain Menu Template or Business Function.Possible options for KeyType are :AccessIdTypeCodeBusinessFunctionEntityMenuTemplatePortOfOrigin
     */
    @WebMethod(operationName = "IsUserAuthorizedEx")
    @WebResult(name = "ResponseBoolRoot", targetNamespace = "urn:Humana:WebSecurity:SL:WebService:MessageTypes", partName = "Body")
    public humana.websecurity.sl.webservice.messagetypes.ResponseBool isUserAuthorizedEx(
        @WebParam(partName = "akaName", name = "akaName", targetNamespace = "")
        java.lang.String akaName,
        @WebParam(partName = "key", name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(partName = "keyType", name = "keyType", targetNamespace = "")
        java.lang.String keyType,
        @WebParam(partName = "sessionId", name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );
}
